import { Model } from "objection";

export class DeliveryOrderPending extends Model {
  static tableName = 'DeliveryOrderPending';
  order_id: string;
  order_counter: number;
  user_id: string;
  channel_id: number;
  channel_order_id: string;
  status: string;
  created_datetime: string;
  delivery_datetime: string;
  delivery_period: string;
  method_id: number;
  completed_datetime: string;
  order_num: string;
  recipient_name: string;
  recipient_email: string;
  address: string;
  contact_no: string;
  postal_code: string;
  payment_mode: string;
  discount_value: number;
  coupon_value: number;
  shipping_cost: number;
  handling_cost: number;
  gst: number;
  sales_total: number;
  special_request: string;
  exchange_rate: number;
  currency: string;
  tax_id: string;
  address_type: string;
  state: string;
  city: string;
  country_code: string;
  inserted_datetime: string;
  skucache_datetime: string;
  district: string;
  wms_address_id: string;
  wms_division_id: string;
  wms_area_id: string;
  wms_status: string;
  wms_push_datetime: string;
  wms_push_version: number;
  wms_version: number;
  gwp_version: number;
  voucher_seller: number;
  voucher_platform: number;
  voucher_code: string;
  shipping_code: string;
  total_declared_value: number;
}
